// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTQ3HFnk6Jr5N9WkoM0d51GDIJ8hZMnHU',
    appId: '1:989387077624:web:f6e0ce61310f3dcb89880d',
    messagingSenderId: '989387077624',
    projectId: 'nomadcoder-final-project2-hsb',
    authDomain: 'nomadcoder-final-project2-hsb.firebaseapp.com',
    storageBucket: 'nomadcoder-final-project2-hsb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHnU9sX3u_3PK25SoTRH2eBDHqctCEBn8',
    appId: '1:989387077624:android:2022cd8c5831842989880d',
    messagingSenderId: '989387077624',
    projectId: 'nomadcoder-final-project2-hsb',
    storageBucket: 'nomadcoder-final-project2-hsb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK_VBE0dBx2Z4bOoRzbJjzRqtP5AN71Rs',
    appId: '1:989387077624:ios:01ea997946ad694d89880d',
    messagingSenderId: '989387077624',
    projectId: 'nomadcoder-final-project2-hsb',
    storageBucket: 'nomadcoder-final-project2-hsb.firebasestorage.app',
    iosBundleId: 'com.example.nomadcoderFlutterFinalProject2',
  );

}